### Test FxTemplateFiller Function
POST http://localhost:7071/api/FxTemplateFiller
Content-Type: application/json

{
    "title": "CSA",
    "name": "Walter Novoa",
    "city": "Bogotá",
    "profession": "Cloud Solutions Architect",
    "message": "Ready to design",
    "date": "2025-06-23"
  }
