//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenticWebGen.Fx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class base_local : global::System.Configuration.ApplicationSettingsBase {
        
        private static base_local defaultInstance = ((base_local)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new base_local())));
        
        public static base_local Default {
            get {
                return defaultInstance;
            }
        }
    }
}
